CREATE TABLE "open-shuttle_ingestion_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "open-shuttle_ingestion_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"startedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"finishedAt" timestamp with time zone,
	"status" varchar(24) DEFAULT 'running' NOT NULL,
	"discovered" integer DEFAULT 0 NOT NULL,
	"imported" integer DEFAULT 0 NOT NULL,
	"matches" integer DEFAULT 0 NOT NULL,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_match_player" (
	"matchId" text NOT NULL,
	"playerId" text NOT NULL,
	"side" integer NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "open-shuttle_match_player_matchId_playerId_pk" PRIMARY KEY("matchId","playerId")
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_match" (
	"id" text PRIMARY KEY NOT NULL,
	"tournamentId" uuid NOT NULL,
	"matchDate" date,
	"draw" text,
	"round" text,
	"venue" text,
	"score" text,
	"winnerSide" integer,
	"status" varchar(32) DEFAULT 'scheduled' NOT NULL,
	"sourceUrl" text NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_player" (
	"id" text PRIMARY KEY NOT NULL,
	"tournamentId" uuid NOT NULL,
	"sourcePlayerId" varchar(80) NOT NULL,
	"name" text NOT NULL,
	"profileUrl" text NOT NULL,
	"clubId" varchar(80),
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_source_post" (
	"id" text PRIMARY KEY NOT NULL,
	"sourceId" varchar(80) NOT NULL,
	"url" text NOT NULL,
	"publishedAt" timestamp with time zone,
	"text" text,
	"discoveredAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_source" (
	"id" varchar(80) PRIMARY KEY NOT NULL,
	"name" varchar(160) NOT NULL,
	"url" text NOT NULL,
	"pageId" varchar(160),
	"enabled" boolean DEFAULT true NOT NULL,
	"lastCheckedAt" timestamp with time zone,
	"lastError" text
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_tournament_source" (
	"tournamentId" uuid NOT NULL,
	"sourcePostId" text NOT NULL,
	CONSTRAINT "open-shuttle_tournament_source_tournamentId_sourcePostId_pk" PRIMARY KEY("tournamentId","sourcePostId")
);
--> statement-breakpoint
CREATE TABLE "open-shuttle_tournament" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"url" text NOT NULL,
	"startsOn" date,
	"endsOn" date,
	"discoveredAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastImportedAt" timestamp with time zone,
	"lastError" text
);
--> statement-breakpoint
ALTER TABLE "open-shuttle_match_player" ADD CONSTRAINT "open-shuttle_match_player_matchId_open-shuttle_match_id_fk" FOREIGN KEY ("matchId") REFERENCES "public"."open-shuttle_match"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_match_player" ADD CONSTRAINT "open-shuttle_match_player_playerId_open-shuttle_player_id_fk" FOREIGN KEY ("playerId") REFERENCES "public"."open-shuttle_player"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_match" ADD CONSTRAINT "open-shuttle_match_tournamentId_open-shuttle_tournament_id_fk" FOREIGN KEY ("tournamentId") REFERENCES "public"."open-shuttle_tournament"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_player" ADD CONSTRAINT "open-shuttle_player_tournamentId_open-shuttle_tournament_id_fk" FOREIGN KEY ("tournamentId") REFERENCES "public"."open-shuttle_tournament"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_source_post" ADD CONSTRAINT "open-shuttle_source_post_sourceId_open-shuttle_source_id_fk" FOREIGN KEY ("sourceId") REFERENCES "public"."open-shuttle_source"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_tournament_source" ADD CONSTRAINT "open-shuttle_tournament_source_tournamentId_open-shuttle_tournament_id_fk" FOREIGN KEY ("tournamentId") REFERENCES "public"."open-shuttle_tournament"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "open-shuttle_tournament_source" ADD CONSTRAINT "open-shuttle_tournament_source_sourcePostId_open-shuttle_source_post_id_fk" FOREIGN KEY ("sourcePostId") REFERENCES "public"."open-shuttle_source_post"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "match_player_player_idx" ON "open-shuttle_match_player" USING btree ("playerId");--> statement-breakpoint
CREATE INDEX "match_tournament_date_idx" ON "open-shuttle_match" USING btree ("tournamentId","matchDate");--> statement-breakpoint
CREATE UNIQUE INDEX "player_tournament_source_uidx" ON "open-shuttle_player" USING btree ("tournamentId","sourcePlayerId");--> statement-breakpoint
CREATE INDEX "player_name_idx" ON "open-shuttle_player" USING btree ("name");--> statement-breakpoint
CREATE INDEX "source_post_source_idx" ON "open-shuttle_source_post" USING btree ("sourceId");